name: Bentel Absoluta Local
version: "1.1"
slug: absolutalocal
description: "Add-On for interfacing with Bentel Absoluta Alarm Panels through the local network"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  mqtt_broker_ip: ""
  mqtt_username: ""
  mqtt_password: ""
  panel_id: ""
  pin: ""
  panel_ip_address: ""
schema:
  mqtt_broker_ip: str
  mqtt_username: str
  mqtt_password: password
  panel_id: str
  pin: password
  panel_ip_address: str
